from pathlib import Path
path=Path('src/pages/Technicians/TechniciansPage.jsx')
text=path.read_text(encoding='utf-8')
old="""<table className=\"technicians-table\">\n          <thead>\n            <tr>\n              <th>Name</th>\n              <th>Email</th>\n              <th>Department</th>\n              <th>No of Screens</th>\n              <th>Date Joined</th>\n              <th>Last Activity</th>\n            </tr>\n          </thead>\n          <tbody>\n            {sortedTechnicians.map((tech) => {\n              const initials = tech.name\n                .split(' ')\n                .map((segment) => segment[0])\n                .join('')\n                .slice(0, 2)\n                .toUpperCase();\n              return (\n                <tr key={tech.id}>\n                  <td>\n                    <div className=\"technician-table__name\">\n                      <div className=\"technician-table__avatar\">{initials}</div>\n                      <div>\n                        <span className=\"technician-table__name-text\">{tech.name}</span>\n                        <span className={`technician-table__status technician-table__status--${tech.status.toLowerCase()}`}>
                          {tech.status}\n                        </span>\n                      </div>\n                    </div>\n                  </td>\n                  <td>{tech.email}</td>\n                  <td>{tech.department}</td>\n                  <td>{tech.scans.toLocaleString()}</td>\n                  <td>{new Date(tech.joined).toLocaleDateString()}</td>\n                  <td className=\"technician-table__activity\">{tech.last}</td>\n                </tr>\n              );\n            })}\n          </tbody>\n        </table>"""
new="""<table className=\"technicians-table\">\n          <thead>\n            <tr>\n              <th>Name</th>\n              <th>Status</th>\n              <th>Email</th>\n              <th>Department</th>\n              <th>No of Screens</th>\n              <th>Date Joined</th>\n              <th>Last Activity</th>\n              <th>Actions</th>\n            </tr>\n          </thead>\n          <tbody>\n            {sortedTechnicians.map((tech) => {\n              const initials = tech.name\n                .split(' ')\n                .map((segment) => segment[0])\n                .join('')\n                .slice(0, 2)\n                .toUpperCase();\n              return (\n                <tr key={tech.id}>\n                  <td>\n                    <div className=\"technician-table__name\">\n                      <div className=\"technician-table__avatar\">{initials}</div>\n                      <span className=\"technician-table__name-text\">{tech.name}</span>\n                    </div>\n                  </td>\n                  <td>\n                    <span className={`technician-table__status technician-table__status--${tech.status.toLowerCase()}`}>
                      {tech.status}\n                    </span>\n                  </td>\n                  <td>{tech.email}</td>\n                  <td>{tech.department}</td>\n                  <td>{tech.scans.toLocaleString()}</td>\n                  <td>{new Date(tech.joined).toLocaleDateString()}</td>\n                  <td className=\"technician-table__activity\">{tech.last}</td>\n                  <td className=\"technician-table__actions\">\n                    <div className=\"technician-table__row-actions\">\n                      <button type=\"button\" onClick={() => openEditModal(tech)} aria-label=\"Edit technician\">✏️</button>\n                      <button type=\"button\" onClick={() => handleDelete(tech)} aria-label=\"Delete technician\">🗑️</button>\n                    </div>\n                  </td>\n                </tr>\n              );\n            })}\n          </tbody>\n        </table>"""
if old not in text:
    raise SystemExit('old snippet not found')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
