import jsPDF from 'jspdf';

const drawHeader = (pdf, title) => {
  pdf.setFillColor(52, 152, 219);
  pdf.rect(0, 0, 210, 30, 'F');
  pdf.setFontSize(20);
  pdf.setTextColor(255, 255, 255);
  pdf.text('EmbroideryTech', 105, 15, { align: 'center' });
  pdf.setFontSize(14);
  pdf.text(title, 105, 25, { align: 'center' });
};

const drawFooter = (pdf) => {
  pdf.setFillColor(44, 62, 80);
  pdf.rect(20, 270, 170, 25, 'F');
  pdf.setFontSize(9);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Notification summary generated by EmbroideryTech Desktop', 105, 280, { align: 'center' });
};

export const generateNotificationScreensReport = (notification, users = []) => {
  const pdf = new jsPDF();
  drawHeader(pdf, 'Notification Screens Report');
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(127, 140, 141);
  pdf.text(`Generated on ${new Date().toLocaleString()}`, 105, 40, { align: 'center' });

  let y = 60;
  pdf.setFontSize(11);
  pdf.setTextColor(44, 62, 80);
  pdf.text(`Notification: ${notification.title}`, 20, y);
  y += 6;
  pdf.text(`Message: ${notification.message}`, 20, y);
  y += 6;
  pdf.text(`Category: ${notification.type.toUpperCase()}`, 20, y);
  y += 6;
  pdf.text(`Screens: ${notification.scans.length}`, 20, y);

  y += 10;
  notification.scans.forEach((scan, idx) => {
    if (y > 250) {
      pdf.addPage();
      y = 30;
    }
    pdf.setFontSize(11);
    pdf.text(`Screen ${idx + 1}: ${scan.barcode || 'Unknown'}`, 20, y);
    y += 6;
    pdf.setFontSize(10);
    pdf.text(`Technician: ${scan.technicianDisplay || scan.technician || 'Unknown'}`, 25, y);
    y += 5;
    const department = scan.department || users.find(u => u.username === scan.technician)?.department || 'Unknown';
    pdf.text(`Department: ${department}`, 25, y);
    y += 5;
    pdf.text(`Status: ${scan.status || 'Unknown'}`, 25, y);
    y += 5;
    pdf.text(`Time: ${scan.timestamp ? new Date(scan.timestamp).toLocaleString() : 'Unknown'}`, 25, y);
    y += 8;
  });

  drawFooter(pdf);
  const filename = `Screens_${notification.type}_${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(filename);
};
