import jsPDF from 'jspdf';

const drawHeader = (pdf, title, subtitle) => {
  pdf.setFillColor(44, 62, 80);
  pdf.rect(20, 15, 170, 25, 'F');
  pdf.setFontSize(18);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Amrod', 105, 28, { align: 'center' });
  pdf.setFontSize(14);
  pdf.text(title, 105, 38, { align: 'center' });
  pdf.setFontSize(10);
  pdf.setTextColor(163, 184, 211);
  pdf.text(subtitle, 105, 45, { align: 'center' });
};

const writeFooter = (pdf) => {
  pdf.setFillColor(44, 62, 80);
  pdf.rect(20, 250, 170, 25, 'F');
  pdf.setFontSize(9);
  pdf.setTextColor(255, 255, 255);
  pdf.text('This report was generated by Amrod Digital Asset Tracking Management System', 105, 260, { align: 'center' });
  pdf.text('For technical support, contact the IT department', 105, 268, { align: 'center' });
};

export const generateScanReport = (scan) => {
  const pdf = new jsPDF();
  drawHeader(pdf, 'Screen Scan Report', `Barcode ${scan.barcode || 'N/A'}`);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(12);
  pdf.setTextColor(44, 62, 80);

  const rows = [
    ['Barcode', scan.barcode],
    ['Status', scan.status],
    ['Technician', scan.technician || 'Unknown'],
    ['Department', scan.department || 'Unknown'],
    ['Scan Time', scan.timestamp ? new Date(scan.timestamp).toLocaleString() : 'Unknown'],
    ['Scan ID', scan._id || 'Unknown']
  ];

  let y = 80;
  const lineHeight = 12;
  rows.forEach(([label, value]) => {
    pdf.text(`${label}:`, 30, y);
    pdf.text(value || 'Unknown', 90, y);
    y += lineHeight;
  });

  writeFooter(pdf);
  const filename = `Scan_Report_${scan.barcode || 'unknown'}_${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(filename);
};
