import jsPDF from 'jspdf';

const drawHeader = (pdf, subtitle) => {
  pdf.setFillColor(44, 62, 80);
  pdf.rect(20, 15, 170, 25, 'F');
  pdf.setFontSize(18);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Amrod Digital Asset Tracking Management System  ', 105, 28, { align: 'center' });
  pdf.setFontSize(14);
  pdf.text('Session Report', 105, 38, { align: 'center' });
  pdf.setFontSize(10);
  pdf.setTextColor(173, 178, 189);
  pdf.text(subtitle, 105, 44, { align: 'center' });
};

const writeFooter = (pdf) => {
  pdf.setFillColor(44, 62, 80);
  pdf.rect(20, 250, 170, 25, 'F');
  pdf.setFontSize(9);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Generated by Amrod Digital Asset Tracking Management System', 105, 260, { align: 'center' });
  pdf.text('Contact IT for assistance', 105, 268, { align: 'center' });
};

export const generateSessionReport = (session) => {
  const pdf = new jsPDF();
  drawHeader(pdf, `Session ${session._id?.slice(-8) || 'Unknown'}`);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(12);
  pdf.setTextColor(44, 62, 80);

  const rows = [
    ['Technician', session.technician || 'Unknown'],
    ['Department', session.department || 'Unknown'],
    ['Start Time', session.startTime ? new Date(session.startTime).toLocaleString() : 'Unknown'],
    ['End Time', session.endTime ? new Date(session.endTime).toLocaleString() : 'Active'],
    ['Scans', session.scanCount || 0],
    ['Status', session.endTime ? 'Completed' : 'Active']
  ];

  let y = 80;
  rows.forEach(([label, value]) => {
    pdf.text(`${label}:`, 30, y);
    pdf.text(value.toString(), 90, y);
    y += 12;
  });

  writeFooter(pdf);
  const filename = `Session_Report_${session._id?.slice(-8) || Date.now()}.pdf`;
  pdf.save(filename);
};
