import jsPDF from 'jspdf';

const drawHeader = (pdf) => {
  pdf.setFillColor(44, 62, 80);
  pdf.rect(20, 15, 170, 25, 'F');
  pdf.setFontSize(18);
  pdf.setTextColor(255, 255, 255);
  pdf.text('EMBROIDERYTECH', 105, 28, { align: 'center' });
  pdf.setFontSize(14);
  pdf.text('Technician Management Report', 105, 38, { align: 'center' });
};

const drawFooter = (pdf) => {
  pdf.setFillColor(44, 62, 80);
  pdf.rect(20, 250, 170, 25, 'F');
  pdf.setFontSize(9);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Reports generated by the Desktop Management App', 105, 260, { align: 'center' });
};

export const generateTechniciansReport = (technicians = [], filters = {}) => {
  const pdf = new jsPDF();
  drawHeader(pdf);
  pdf.setFontSize(10);
  pdf.setTextColor(127, 140, 141);
  pdf.text(`Generated on ${new Date().toLocaleString()}`, 105, 45, { align: 'center' });

  let y = 60;
  technicians.forEach((tech, idx) => {
    if (y > 250) {
      pdf.addPage();
      y = 30;
    }
    pdf.setFontSize(11);
    pdf.setTextColor(44, 62, 80);
    pdf.text(`Technician ${idx + 1}: ${tech.username || 'Unknown'}`, 20, y);
    y += 6;
    pdf.setFontSize(10);
    pdf.text(`Department: ${tech.department || 'Unknown'}`, 25, y);
    y += 5;
    pdf.text(`Email: ${tech.email || 'N/A'}`, 25, y);
    y += 5;
    pdf.text(`ID: ${tech._id?.slice(-8) || 'Unknown'}`, 25, y);
    y += 8;
  });

  drawFooter(pdf);
  const filename = `Technician_Report_${filters.department || 'all'}_${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(filename);
};
