name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install backend dependencies
      run: cd desktop-backend && npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Build and publish to GitHub Releases
      uses: samuelmeuli/action-electron-builder@v1
      with:
        github_token: ${{ secrets.github_token }}
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      env:
        GH_TOKEN: ${{ secrets.github_token }}
